server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/BreakStones
    username: root
    password: Passw0rd!
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://root:passw0rd@localhost:27017/BreakStones