# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
#mybatis:
#  typeAliasesPackage: com.wimux.breakstones.entity
#  mapperLocations: classpath:config/mapper/*.xml
jdbc:
  type: mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/BreakStones
    username: root
    password: passw0rd!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

